[package]
name = "rust-sandbox"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
image = "0.13.0"
lazy_static = "1.4.0"
rayon = "0.4.0"
